name: moth-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - jupyter=1.0.0
  - jupyterlab=4.0.11
  - pillow=10.3.0
  - tqdm=4.66.4
  - pyyaml=6.0.1
  - pip=24.0
  - pip:
    - torch==2.6.0+cpu
    - torchvision==0.21.0+cpu
    - timm==1.0.16
    - opencv-python==4.12.0.88
    - pytorch-grad-cam==1.5.5